function [ C_ni ] = C_ni_ni_function(mass_v,inertia_v, ni, V )

[u, v, w] = ni(1,1:3);
[p, q, r] = ni(1,4:6);

C_ni = [0 -mass_v(2)*r mass_v(3)*q 0 0 0;...
        mass_v(1)*r 0 -mass_v(3)*p 0 0 0;...
        -mass_v(1)*q mass_v(2)*p 0 0 0 0;...
        0 (Yv-Zz)*w 0 inertia_v(4)*q -inertia_v(2)*r inertia_v(3)*q;...
        0 0 (Zz-Xu)*u -inertia_v(4)*p-inertia_v(1)*r 0 inertia_v(3)*p+inertia_v(4)*r;...
        (Xu-Yv)*v 0 0 -inertia_v(1)*q inertia_v(2)*p -inertia_v(4)*q];
    
end

